# Generated by Django 6.1.1 on 2026-09-22 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colaboradores', '0001_initial'),
        ('frota', '0001_initial'),
        ('motoristas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(max_length=100, verbose_name='Setor')),
                ('atividade', models.CharField(max_length=150, verbose_name='Atividade')),
                ('origem', models.CharField(max_length=150, verbose_name='Origem')),
                ('destino', models.CharField(max_length=150, verbose_name='Destino')),
                ('data', models.DateField(verbose_name='Data')),
                ('horario_saida', models.TimeField(verbose_name='Horário de saída')),
                ('horario_retorno', models.TimeField(verbose_name='Horário de retorno')),
                ('quantidade_passageiros', models.IntegerField(verbose_name='Quantidade de passageiros')),
                ('status', models.CharField(choices=[('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='confirmada', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('protocolo_unico', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Protocolo')),
                ('motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='motoristas.motorista')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colaboradores.colaborador')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='frota.veiculo')),
            ],
            options={
                'ordering': ['-data', '-horario_saida'],
            },
        ),
    ]
