# Generated by Django 6.1.1 on 2026-09-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True, verbose_name='Placa')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('tipo', models.CharField(choices=[('leve', 'Leve (Até 4 passageiros)'), ('coletivo', 'Coletivo (Até 18 passageiros)')], max_length=20, verbose_name='Tipo')),
                ('capacidade_maxima', models.IntegerField(verbose_name='Capacidade máxima')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Veículo da frota',
                'ordering': ['placa'],
            },
        ),
    ]
